</div>
</body>
<footer>
    <h3 style="margin:0;">Contact :</h3>
    <div class="container-footer">
        <div style="width: 25%;align-items: center;display: flex;justify-content:center;">
            <p>Secrétaire : 07 68 88 29 03 <br>
                <a  href="mailto:artanime.secretariat@gmail.com">artanime.secretariat@gmail.com</a>
            </p>
        </div>
        <div style="width: 25%;align-items: center;display: flex;justify-content:center;">
            <p>Président :​ 06 11 18 14 42 <br> 
                <a  href="mailto:artanime@free.fr">artanime@free.fr </a> 
            </p>
        </div>
    </div>
</footer>